# Generated by Django 4.2.2 on 2024-05-20 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0002_remove_user_username_user_first_name_user_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(default="Default address", max_length=150),
        ),
    ]
